// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push_polling.proto

#ifndef PROTOBUF_push_5fpolling_2eproto__INCLUDED
#define PROTOBUF_push_5fpolling_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "weizhu.pb.h"
// @@protoc_insertion_point(includes)

namespace weizhu {
namespace push {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_push_5fpolling_2eproto();
void protobuf_AssignDesc_push_5fpolling_2eproto();
void protobuf_ShutdownFile_push_5fpolling_2eproto();

class GetPushMsgRequest;
class GetPushMsgResponse;

// ===================================================================

class GetPushMsgRequest : public ::google::protobuf::MessageLite {
 public:
  GetPushMsgRequest();
  virtual ~GetPushMsgRequest();

  GetPushMsgRequest(const GetPushMsgRequest& from);

  inline GetPushMsgRequest& operator=(const GetPushMsgRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const GetPushMsgRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GetPushMsgRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GetPushMsgRequest* other);

  // implements Message ----------------------------------------------

  GetPushMsgRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const GetPushMsgRequest& from);
  void MergeFrom(const GetPushMsgRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 push_seq = 1;
  inline bool has_push_seq() const;
  inline void clear_push_seq();
  static const int kPushSeqFieldNumber = 1;
  inline ::google::protobuf::int64 push_seq() const;
  inline void set_push_seq(::google::protobuf::int64 value);

  // required int32 msg_size = 2;
  inline bool has_msg_size() const;
  inline void clear_msg_size();
  static const int kMsgSizeFieldNumber = 2;
  inline ::google::protobuf::int32 msg_size() const;
  inline void set_msg_size(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:weizhu.push.GetPushMsgRequest)
 private:
  inline void set_has_push_seq();
  inline void clear_has_push_seq();
  inline void set_has_msg_size();
  inline void clear_has_msg_size();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 push_seq_;
  ::google::protobuf::int32 msg_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_push_5fpolling_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_push_5fpolling_2eproto();
  #endif
  friend void protobuf_AssignDesc_push_5fpolling_2eproto();
  friend void protobuf_ShutdownFile_push_5fpolling_2eproto();

  void InitAsDefaultInstance();
  static GetPushMsgRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetPushMsgResponse : public ::google::protobuf::MessageLite {
 public:
  GetPushMsgResponse();
  virtual ~GetPushMsgResponse();

  GetPushMsgResponse(const GetPushMsgResponse& from);

  inline GetPushMsgResponse& operator=(const GetPushMsgResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const GetPushMsgResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GetPushMsgResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GetPushMsgResponse* other);

  // implements Message ----------------------------------------------

  GetPushMsgResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const GetPushMsgResponse& from);
  void MergeFrom(const GetPushMsgResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .weizhu.PushMessage push_msg = 1;
  inline int push_msg_size() const;
  inline void clear_push_msg();
  static const int kPushMsgFieldNumber = 1;
  inline const ::weizhu::PushMessage& push_msg(int index) const;
  inline ::weizhu::PushMessage* mutable_push_msg(int index);
  inline ::weizhu::PushMessage* add_push_msg();
  inline const ::google::protobuf::RepeatedPtrField< ::weizhu::PushMessage >&
      push_msg() const;
  inline ::google::protobuf::RepeatedPtrField< ::weizhu::PushMessage >*
      mutable_push_msg();

  // required bool has_more = 2;
  inline bool has_has_more() const;
  inline void clear_has_more();
  static const int kHasMoreFieldNumber = 2;
  inline bool has_more() const;
  inline void set_has_more(bool value);

  // @@protoc_insertion_point(class_scope:weizhu.push.GetPushMsgResponse)
 private:
  inline void set_has_has_more();
  inline void clear_has_has_more();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::weizhu::PushMessage > push_msg_;
  bool has_more_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_push_5fpolling_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_push_5fpolling_2eproto();
  #endif
  friend void protobuf_AssignDesc_push_5fpolling_2eproto();
  friend void protobuf_ShutdownFile_push_5fpolling_2eproto();

  void InitAsDefaultInstance();
  static GetPushMsgResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// GetPushMsgRequest

// required int64 push_seq = 1;
inline bool GetPushMsgRequest::has_push_seq() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetPushMsgRequest::set_has_push_seq() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetPushMsgRequest::clear_has_push_seq() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetPushMsgRequest::clear_push_seq() {
  push_seq_ = GOOGLE_LONGLONG(0);
  clear_has_push_seq();
}
inline ::google::protobuf::int64 GetPushMsgRequest::push_seq() const {
  // @@protoc_insertion_point(field_get:weizhu.push.GetPushMsgRequest.push_seq)
  return push_seq_;
}
inline void GetPushMsgRequest::set_push_seq(::google::protobuf::int64 value) {
  set_has_push_seq();
  push_seq_ = value;
  // @@protoc_insertion_point(field_set:weizhu.push.GetPushMsgRequest.push_seq)
}

// required int32 msg_size = 2;
inline bool GetPushMsgRequest::has_msg_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetPushMsgRequest::set_has_msg_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetPushMsgRequest::clear_has_msg_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetPushMsgRequest::clear_msg_size() {
  msg_size_ = 0;
  clear_has_msg_size();
}
inline ::google::protobuf::int32 GetPushMsgRequest::msg_size() const {
  // @@protoc_insertion_point(field_get:weizhu.push.GetPushMsgRequest.msg_size)
  return msg_size_;
}
inline void GetPushMsgRequest::set_msg_size(::google::protobuf::int32 value) {
  set_has_msg_size();
  msg_size_ = value;
  // @@protoc_insertion_point(field_set:weizhu.push.GetPushMsgRequest.msg_size)
}

// -------------------------------------------------------------------

// GetPushMsgResponse

// repeated .weizhu.PushMessage push_msg = 1;
inline int GetPushMsgResponse::push_msg_size() const {
  return push_msg_.size();
}
inline void GetPushMsgResponse::clear_push_msg() {
  push_msg_.Clear();
}
inline const ::weizhu::PushMessage& GetPushMsgResponse::push_msg(int index) const {
  // @@protoc_insertion_point(field_get:weizhu.push.GetPushMsgResponse.push_msg)
  return push_msg_.Get(index);
}
inline ::weizhu::PushMessage* GetPushMsgResponse::mutable_push_msg(int index) {
  // @@protoc_insertion_point(field_mutable:weizhu.push.GetPushMsgResponse.push_msg)
  return push_msg_.Mutable(index);
}
inline ::weizhu::PushMessage* GetPushMsgResponse::add_push_msg() {
  // @@protoc_insertion_point(field_add:weizhu.push.GetPushMsgResponse.push_msg)
  return push_msg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::weizhu::PushMessage >&
GetPushMsgResponse::push_msg() const {
  // @@protoc_insertion_point(field_list:weizhu.push.GetPushMsgResponse.push_msg)
  return push_msg_;
}
inline ::google::protobuf::RepeatedPtrField< ::weizhu::PushMessage >*
GetPushMsgResponse::mutable_push_msg() {
  // @@protoc_insertion_point(field_mutable_list:weizhu.push.GetPushMsgResponse.push_msg)
  return &push_msg_;
}

// required bool has_more = 2;
inline bool GetPushMsgResponse::has_has_more() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetPushMsgResponse::set_has_has_more() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetPushMsgResponse::clear_has_has_more() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetPushMsgResponse::clear_has_more() {
  has_more_ = false;
  clear_has_has_more();
}
inline bool GetPushMsgResponse::has_more() const {
  // @@protoc_insertion_point(field_get:weizhu.push.GetPushMsgResponse.has_more)
  return has_more_;
}
inline void GetPushMsgResponse::set_has_more(bool value) {
  set_has_has_more();
  has_more_ = value;
  // @@protoc_insertion_point(field_set:weizhu.push.GetPushMsgResponse.has_more)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace push
}  // namespace weizhu

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_push_5fpolling_2eproto__INCLUDED
